config/routes.rb
Rails.application.routes.draw do
  root 'statics#index'
  get '/about', to: 'statics#about'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :followings, :followers
    end
  end
  resources :tasks, only: [:index, :show, :create, :update, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user
  before_action :set_user

  def create
    following = current_user.follow(@user)
    if following.save
      respond_to do |format|
        format.html
        format.js
      end
    else
      flash[:danger] = "YOU FAILED TO FOLLOW"
      redirect_to @user
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      respond_to do |format|
        format.html
        format.js
      end
    else
      flash[:danger] = "YOU FAILED TO FOLLOW"
      redirect_to @user
    end
  end

  private

  def set_user
    @user = User.find(params[:relationship][:follow_id])
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'relationships/unfollow' %>
    <% else %>
      <%= render 'relationships/following' %>
    <% end %>
  </div>
<% end %>

app/views/relationships/_following.html.erb
<%= form_for(current_user.relationships.build, remote: true) do |f| %>
  <%= f.hidden_field :follow_id, value: @user.id %>
  <%= f.submit 'Follow', class: "btn btn-primary" %>
<% end %>

app/views/relationships/_stats.html.erb
<div class="stats text-light d-flex justify-content-center mt-4">
  <div class="btn btn-primary btn-sm mx-3">
    <strong id="following" class="stat d-block"><%= @user.followings.count %></strong>
    <%= link_to "following", followings_user_path(@user), class:"text-light"%>
  </div>
  <div class="btn btn-primary  btn-sm">
    <strong id="followers" class="stat d-block"><%= @user.followers.count %></strong>
    <%= link_to "followers", followers_user_path(@user), class:"text-light" %>
  </div>
</div>

app/views/relationships/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(follow_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.hidden_field :follow_id, value: @user.id %>
  <%= f.submit 'Unfollow', class: "btn btn-primary" %>
<% end %>

app/views/relationships/create.js.erb
$('#follow_form').html("<%= j(render 'unfollow') %>")
$('#followers').html("<%= @user.followers.count %>")

app/views/relationships/destroy.js.erb
$('#follow_form').html("<%= j(render 'following') %>")
$('#followers').html("<%= @user.followers.count %>")