config/routes.rb
Rails.application.routes.draw do
  root 'statics#index'
  get '/about', to: 'statics#about'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :followings, :followers
    end
  end
  resources :tasks, only: [:index, :show, :create, :update, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="inner bg-dark d-flex flex-column justify-content-center p-4">
    <p class="text-center m-0"><span class="text-light">TODO LIST</span></p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="header">
  <div class="inner">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-5">
      <h1><%= link_to "TO DO LIST", root_path, class: "navbar-brand text-light" %></h1>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
        <% if logged_in? %>
          <li class="nav-item active mx-3">
            <%= link_to "LOG OUT", logout_path, class:"nav-link text-light", method: :delete %>
          </li>
          <li class="nav-item active mx-3">
            <%= link_to "USERS", users_path, class:"nav-link text-light" %>
          </li>
          <li class="nav-item active mx-3">
            <%= link_to "POSTS", tasks_path, class:"nav-link text-light" %>
          </li>
          <li class="nav-item active mx-3">
            <div class="dropdown">
              <a id="dropdownMenu" class="dropdown-toggle nav-link text-light" data-toggle="dropdown" aria-haspopup="true" aria-expanded=false>ACCOUNT</a>
              <ul class="dropdown-menu bg-dark ml-auto" aria-labelledby="dropdownMenu">
                <li><%= link_to "PROFILE", user_path(current_user), class:"nav-link text-light" %></li>
                <li><%= link_to "SETTING", edit_user_path(current_user), class:"nav-link text-light" %></li>
              </ul>
            </div>
          </li>
        <% else %>
        <li class="nav-item active mx-3">
            <%= link_to "HOME", root_path, class:"nav-link text-light" %>
          </li>
         <li class="nav-item active mx-3">
            <%= link_to "ABOUT", about_path, class:"nav-link text-light" %>
          </li>
          <li class="nav-item active mx-3">
            <%= link_to "SIGN UP", new_user_path, class:"nav-link text-light" %>
          </li>
          <li class="nav-item active mx-3">
            <%= link_to "LOG IN", login_path, class:"nav-link text-light" %>
          </li>
        <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
      <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>